export const SET_ACTIVATE_PAGE = 'SET_ACTIVATE_PAGE';

export const SET_CURRENT_TYPE = 'SET_CURRENT_TYPE'

export const SET_ANSWERS = 'SET_ANSWERS'

export const SET_STATE_TEMPLATE = 'SET_STATE_TEMPLATE'