
// FETCH POSTS
export const FETCH_POSTS = "FETCH_POSTS"

// PAGINATION
export const NEXT_CURSOR = "NEXT_CURSOR";

// POST AMT INDICATOR
export const POSTS_FINISHED = "POSTS_FINISHED";

// UPVOTED IDS
export const SAVE_POST_IDS = "SAVE_POST_IDS";

// Will show toasts messages
export const SHOW_ALERT = "SHOW_ALERT";

// SCROLL RESTORATION
export const SAVE_SCROLL_POSITION = "SAVE_SCROLL_POSITION";
