
export const SET_UPLOAD = 'SET_UPLOAD';

export const SET_UPLOAD_RESPONSE = 'SET_UPLOAD_RESPONSE';

export const SET_CURRENT_COMPONENT = 'SET_CURRENT_COMPONENT';

export const SET_TEST_MODAL = "SET_TEST_MODAL";

export const SET_UPLOAD_MODAL = "SET_UPLOAD_MODAL";

export const SET_DRAWER_MODAL = "SET_DRAWER_MODAL";

export const SET_ERR_MESSAGE = "SET_ERR_MESSAGE";
